### PR TITLE
Create new 32-bit and 64-bit windows installers

### PR DESCRIPTION
**Pull request by mthierman**

### CODE REVIEW

**Comment by baconpaul** [comment]
Great!

Will azure run these or are they purely additive and we need to set up pipelines?

**Comment by mthierman** [comment]
I think if we replace line 165 where we run ISCC:

```
iscc //Obuild\\product //Fstochas_windows_installer //DSTOCHAS_VERSION=${STOCHAS_VERSION}.${GH} "install\\win\\install.iss"
```

with this:

```
iscc //Obuild\\product //Fstochas_windows_installer64 //DMyAppVersion=${STOCHAS_VERSION}.${GH} //DSTOCHAS_SRC="..\..\" //DSTOCHAS_BIN="..\..\build\stochas_artefacts\Release" "install\\win\\stochas64.iss"
iscc //Obuild\\product //Fstochas_windows_installer32 //DMyAppVersion=${STOCHAS_VERSION}.${GH} //DSTOCHAS_SRC="..\..\" //DSTOCHAS_BIN="..\..\build32\stochas_artefacts\Release" "install\\win\\stochas32.iss"
```

This should build 32 and 64 bit installers instead. And should publish with the existing windows task since that publishes the whole build/product folder already, if I'm understanding that task properly.

**Comment by mthierman** [comment]
I should also check what happens when I run this over an old install in case we need a cleanup task or something

**Comment by mthierman** [comment]
I've revisited this and don't think we should delete files from an existing install, so I think we either merge this or keep the original 32bit/64 bit install and possibly update that instead. Thoughts?

**Comment by baconpaul** [comment]
Any reason to not clean up the prior install? It’s not user data right just installed assets?

i should do the signed mac installer stuff here too like we do for the other properties. I’ll peek at that this week 

oh and I should fix that zoom thing and turn in clap builds!

**Comment by mthierman** [comment]
If we delete the files it still leaves an entry in add/remove programs (since it's different GUID)

**Comment by baconpaul** [comment]
Can you whack the registry in the new install script? (Shudder)

**Comment by mthierman** [comment]
I added a PowerShell script to plumb the registry and run any previous uninstaller, should work on 32bit and 64bit Windows.

**Pull request closed without merging**
